width = 256
height = 256

title = [113, 5]

[background]
type = "texture"
size = [174, 175]

[texture_nutrition_body]
type = "texture"
size = [4, 78]
uv = [174, 7]

[texture_nutrition_head]
type = "texture"
size = [4, 2]
uv = [174, 5]
position = [164, 5]

[texture_nutrition_tail]
type = "texture"
size = [4, 2]
uv = [174, 85]
position = [164, 85]

[texture_slot_progress]
type = "texture"
size = [18, 1]
uv = [0, 175]

[inventory]
type = "slots"
count = [3, 9]
position = [7, 94]

[selection]
type = "slots"
count = 9
position = [7, 152]

[in0]
type = "slot"
position = [25, 12]

[in1]
type = "slot"
position = [16, 39]

[in2]
type = "slot"
position = [25, 64]

[in3]
type = "slot"
position = [58, 70]

[in4]
type = "slot"
position = [91, 64]

[in5]
type = "slot"
position = [100, 39]

[in6]
type = "slot"
position = [91, 12]

[in7]
type = "slot"
position = [58, 6]

[out]
type = "slots"
count = 9
offset = 4
position = [58, 39]

[feed]
type = "slot"
position = [145, 70]

[nutrition_progress]
type = "progress"
position = [164, 7]
texture_filled = "texture_nutrition_body"
direction = "vertical"

[progress0]
type = "progress"
position = [24, 29]
texture_filled = "texture_slot_progress"

[progress1]
type = "progress"
position = [15, 56]
texture_filled = "texture_slot_progress"

[progress2]
type = "progress"
position = [24, 81]
texture_filled = "texture_slot_progress"

[progress3]
type = "progress"
position = [57, 87]
texture_filled = "texture_slot_progress"

[progress4]
type = "progress"
position = [90, 81]
texture_filled = "texture_slot_progress"

[progress5]
type = "progress"
position = [99, 56]
texture_filled = "texture_slot_progress"

[progress6]
type = "progress"
position = [90, 29]
texture_filled = "texture_slot_progress"

[progress7]
type = "progress"
position = [57, 23]
texture_filled = "texture_slot_progress"
