width = 256
height = 256

title = [113, 5]

[background]
type = "texture"
size = [225, 181]

[progress_filled]
type = "texture"
size = [17, 24]
position = [0, 181]

[inventory]
type = "slots"
count = [3, 9]
position = [31, 98]

[selection]
type = "slots"
count = 9
position = [31, 156]

[in]
type = "slots"
count = 9
offset = 4
position = [7, 26]

[out]
type = "slots"
count = 9
offset = 4
position = [7, 73]

[feed]
type = "slot"
position = [202, 48]

[progress0]
type = "progress"
position = [5, 44]
filled_texture = "progress_filled"
direction = "vertical"

[progress1]
type = "progress"
position = [27, 44]
filled_texture = "progress_filled"
direction = "vertical"

[progress2]
type = "progress"
position = [50, 44]
filled_texture = "progress_filled"
direction = "vertical"

[progress3]
type = "progress"
position = [72, 44]
filled_texture = "progress_filled"
direction = "vertical"

[progress4]
type = "progress"
position = [94, 44]
filled_texture = "progress_filled"
direction = "vertical"

[progress5]
type = "progress"
position = [116, 44]
filled_texture = "progress_filled"
direction = "vertical"

[progress6]
type = "progress"
position = [139, 44]
filled_texture = "progress_filled"
direction = "vertical"

[progress7]
type = "progress"
position = [161, 44]
filled_texture = "progress_filled"
direction = "vertical"

[progress8]
type = "progress"
position = [183, 44]
filled_texture = "progress_filled"
direction = "vertical"
