# Gui 材质描述文件 模板（初稿）
# 整个文档格式为 TOML，文件名与材质名相同，且位于同一目录下
# 文档暂定 point, texture, slot, slots, progress 五种类型

# 图片文件尺寸
width = 256
height = 256

# 点
[a_point]
type = "point"
position = [0, 0]

# 直接的整型数组也可以表示一个点
title = [113, 5]

# 一个图形元素
[progress_filled]
type = "texture"
# 大小，类型 整形*2，单位 像素
size = [17, 24]
# 左上角位置，类型 整形*2，单位 像素
# 可省略，默认 [0, 0]
position = [0, 181]

[background]
type = "texture"
size = [225, 181]

# 一个物品框
[leaves]
type = "slot"
# 大小，类型 整形*2，单位 像素
# 可省略，默认 18
size = 18
# 左上角位置，类型 整形*2，单位 像素
position = [201, 79]

# 一组物品框
[inventory]
type = "slots"
# 大小，类型 整形，单位 像素
# 可省略，默认 18
size = 18
# 数量，类型 整形，该实例表示 3 行 9 列
# 可简写为一个 整形 n，表示 [1, n] 或 [n, 1]，由 direction 属性控制
# 可省略 默认 [1, 1]
count = [3, 9]
# 左上角位置，类型 整形，单位 像素
position = [30, 97]
# 两个 slot 之间的间隔，类型 整形，单位 像素
# 可简写为一个 整形 n，表示 [n, 0] 或 [0, n]，由 direction 属性控制
# 可省略，默认 [0, 0]
offset = [0, 0]
# 方向，可选 horizontal/vertical
# 可省略，默认 horizontal
direction = "horizontal"

[selection]
type = "slots"
count = 9 # [1, 9]
position = [30, 155]

[in]
type = "slots"
count = 9 # [1, 9]
offset = 4 # [4, 0]
position = [6, 25]

[out]
type = "slots"
count = 9
offset = 4
position = [6, 72]

# 一个过程动画，类似熔炉的箭头
[progress0]
type = "progress"
# 左上角位置
position = [5, 44]
# 进度为 0% 的材质名，类型：字符串，必须指向一个 type = "texture" 的表
# 可省略，可为空，表示无对应材质
begin_texture = ""
# 进度为 100% 的材质名，类型：字符串，必须指向一个 type = "texture" 的表
finished_texture = "progress_filled"
# 方向，可选 horizontal/vertical/-horizontal/-vertical
# 可省略，默认 horizontal，即自左向右填充，带有 - 符号的表示相反方向（自右向左/自下而上）
direction = "horizontal"

[progress1]
type = "progress"
position = [27, 44]
filled_texture = "progress_filled"
